### ISSUE TITLE
Task: provide zoom for team members 

### ISSUE THREAD

**Issue by sjinko** [CUPUM/.github#12]
### Task description

 @rsdmu informs that UdeM does not provide access to Zoom anymore to its collaborators. As the primary online conference to at the Chair, we check if we can get access back for the main collaborators. 

### List of actions

- [x] Action: check with IT if zoom access discontinued or suspended
- [ ] Action: Specify requirements
- [x] Action: check pricing
- [ ] Action: check if Faculty can take charge
- [ ] Action: …

**Comment by sjinko** [comment]
Hi @iolyd  could you look into this. I’m surprised we did not get any email to notify us. Also, we have many upcoming meetings on zoom so we need to act fast

**Comment by rsdmu** [comment]
My umontreal account hints that you are limited to 40 mins:
<img width="1461" alt="image" src="https://github.com/CUPUM/.github/assets/113534995/e532c15a-f898-40ec-8062-1beaaf8c04f1">

**Comment by iolyd** [comment]
This appears to be because @rsdmu has a "student" license (Rashid, could you confirm this from within your account?). Employees can still create meetings with much more permissive settings.

See https://wiki.umontreal.ca/display/SIE/Zoom# for more info.

**Comment by iolyd** [comment]
Before I can proceed with the other actions, I would need more info on your requirements @sjinko and @rsdmu. For example, if I'm not mistaken @SarahTannir found out that we can fill out a form to request a special account for hosting webinars without constraints such as the 40 minute limit Rashid faces.

**Comment by rsdmu** [comment]
Hi @iolyd, yes, I can confirm that my account is registered as a student. It is surprisingly weird; on wiki.umontreal, it states that since July 2022, meetings have been limited to 40 minutes, yet I had meetings on my account longer than an hour in April 2024.

**Comment by sjinko** [comment]
@rsdmu perhaps because you are not currently under contract?

If it is a matter of having/not having a contract at the time of the scheduling, I suggest we find a way to always have someone under contract create the meetings. Alternatively, for research assistants, this might simply mean always creating semester-long contracts.

**Comment by rsdmu** [comment]
@sjinko, that seems to be the best explanation. Maybe @iolyd can help further verify it.

**Comment by SarahTannir** [comment]
Hello!
@iolyd I filled the form and TI responded that UdeM does not have access to the Zoom Webinar.

**Comment by SarahTannir** [comment]
Link to the plans and pricing: https://zoom.us/pricing/events (business or education)

**Comment by iolyd** [comment]
I sent a TI ticket describing our concerns, asking for more detailed conditions dictating access to the non-student licence and if there was any way for students to use a less restrictive plan through the university. But it may take some time before we get any feedback.

@sjinko You mentioned important upcoming meetings planned for zoom, can you or an _employee_ working on concerned projects organize said meetings until we clarify the stance of the university. Else should we purchase an account?

**Comment by sjinko** [comment]
If we are correct and this only affects accounts not under contract, it suffit be fine. The only meetings that might be problematic might be the UNIC meetings organized by @rsdmu 

For those, we can use our personal meeting room:

Shin Koseki is inviting you to a scheduled Zoom meeting.

Topic: Shin Koseki's Personal Meeting Room

Join Zoom Meeting
https://umontreal.zoom.us/j/5146065658?pwd=dElLeWVxcnlLOGt2RG1IMFFWbUtUQT09

Meeting ID: 514 606 5658
Passcode: 6158598
One tap mobile
+15873281099,,5146065658# Canada
+16473744685,,5146065658# Canada

Dial by your location
        +1 587 328 1099 Canada
        +1 647 374 4685 Canada
        +1 647 558 0588 Canada
        +1 778 907 2071 Canada
        +1 204 272 7920 Canada
        +1 438 809 7799 Canada
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
        +1 646 558 8656 US (New York)
        +1 669 900 6833 US (San Jose)
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Washington DC)
Meeting ID: 514 606 5658
Find your local number: https://umontreal.zoom.us/u/kcKyW1zES6
