### ISSUE TITLE
Task: prolonger le contrat de R. Mushkani de 68 heures du 1er au 29 mars

### ISSUE THREAD

**Issue by sjinko** [CUPUM/.github#5]
### Task description

Dans l’attente de la réponse du financement de Mitacs pour son stage au Mila, nous prolongerons le contrat de R. Mushkani de 68 heures du 1er au 29 mars 2024 sur le même fonds que précédemment

### List of actions

- [ ] Action: éditer le fichier Excel
- [ ] Action: envoyer le fichier Excel à I. Couillard
- [ ] Action: produire une nouvelle lettre de charge
