### ISSUE TITLE
Task: Relire et commenter manuscrit JL Hamelin

### ISSUE THREAD

**Issue by sjinko** [CUPUM/.github#6]
### Task description

Soumis le 13 mars par courriel

### List of actions

- [ ] Action: lecture rapide
- [ ] Action: lecture commentée
- [ ] Meet: In person with JL Hamelin on ???
